#!/bin/sh

export ARCH=arm
export CROSS_COMPILE=arm-none-linux-gnueabi-
export PATH=/opt/arm-2009q3/bin:$PATH

#INSTALL_BINDIR=/home/yhoh/fastboot_image
KERNEL_IMAGE=zImage

# Default kernel configurations
#make qt210_ICS404_mrvl8787_defconfig
#make qt210_ICS404_mrvl8787_HX8526_defconfig
KERNEL_CONFIG=$2

INSTALL_BINDIR=../image
 
#{
CPU_JOB_NUM=$(grep processor /proc/cpuinfo | awk '{field=$NF};END{print field+2}')
START_TIME=`date +%s`
#sudo apt-get install libncurses5-dev
case "$1" in
clean)
    echo make -j$CPU_JOB_NUM mrproper
	cp .config arch/arm/configs/$KERNEL_CONFIG
	cp .config config.sav
    make -j$CPU_JOB_NUM mrproper
    ;;
config)
    echo make -j$CPU_JOB_NUM menuconfig
    make -j$CPU_JOB_NUM menuconfig
    ;;
defconfig)
    if [ "$2" ] ; then
        KERNEL_CONFIG=$2
    fi
    echo make -j$CPU_JOB_NUM $KERNEL_CONFIG
    make -j$CPU_JOB_NUM $KERNEL_CONFIG
    ;;
all|*)
    echo make -j$CPU_JOB_NUM
    make -j$CPU_JOB_NUM
    if [ $? != 0 ] ; then
	    exit 1
    fi
    if [ "$2" ] ; then
        INSTALL_BINDIR=$2
    fi
    if [ $INSTALL_BINDIR ] ; then
        echo cp -a arch/arm/boot/$KERNEL_IMAGE $INSTALL_BINDIR/$KERNEL_IMAGE
        cp -a arch/arm/boot/$KERNEL_IMAGE $INSTALL_BINDIR/$KERNEL_IMAGE
    fi
    ;;
esac

END_TIME=`date +%s`
echo "Total compile time is $((($END_TIME-$START_TIME)/60)) minutes $((($END_TIME-$START_TIME)%60)) seconds"
#} 2>&1 |tee b.out
